name: Build and run

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - id: files
      uses: jitterbit/get-changed-files@v1
      with:
        format: 'csv'
    - run: |
        mapfile -d ',' -t added_modified_files < <(printf '%s,' '${{ steps.files.outputs.added_modified }}')
        for added_modified_file in "${added_modified_files[@]}"; do
          echo "Do something with this ${added_modified_file}."
        done
        git branch
    - name: Test demo augmentations
      run: python example.py
#    - name: Commit and push generated image
#      run: |-
#        git diff
#        git config --global user.email "image-bot@example.com"
#        git config --global user.name "image-bot"
#        git add *.png && git commit -m "generated images"
#        git push

    - name: Commit and push image on branch
      run : |-
        git config --global user.email "image-bot@example.com"
        git config --global user.name "image-bot"
        echo "Checking for uncommitted changes in the git working tree."
        if ! git diff --quiet
        then

          echo "INPUT_BRANCH value: $INPUT_BRANCH";
          # Switch to branch from current Workflow run
          git checkout $INPUT_BRANCH
          git add .
          git commit -m "generated output from image-bot"
          git push --set-upstream origin "HEAD:$INPUT_BRANCH"
        else
            echo "Working tree clean. Nothing to commit."
        fi