name: Build and run

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ github.head_ref }}
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - id: files
      uses: jitterbit/get-changed-files@v1
      with:
        format: 'csv'
    - run: |
        mapfile -d ',' -t added_modified_files < <(printf '%s,' '${{ steps.files.outputs.added_modified }}')
        for added_modified_file in "${added_modified_files[@]}"; do
          if [ file $added_modified_file |grep -qE 'image|bitmap' ] || [ -e "originals/$added_modified_file" ]; then
            echo "File '$added_modified_file' is an image and is original"
            python cyclegan_generation.py ${added_modified_file}
          fi
        done

    - name: Commit and push generated image
      run: |-
        git diff
        git ls-files -o
        git config --global user.email "image-bot@example.com"
        git config --global user.name "image-bot"
        git add *.png && git commit -m "generated images"
        git push
